name: Pull Request Workflow

on: [push, pull_request]
name: Test
jobs:
  unit_tests:
    runs_on: ubuntu-16.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: go1.15.5
